version: '3.8'

services:
  postgres:
    image: postgres:17.2
    container_name: postgres17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: XXXXX
      POSTGRES_DB: cs3660db
    ports:
      - "5432:5432"
    volumes:
      - ./docker/data:/var/lib/postgresql/data
    restart: unless-stopped
